- hosts: all
  tasks:
    - name: update packages
      command: apt update -y
    - name: install apache2
      package: name=apache2 state=latest
    - name: configure
      shell: "echo Welcome to WeiLiSue Server > /var/www/html/index.html"
    - name: start service
      service: name=apache2 state=started
    - name: add user
      user: name=weilisue state=present
