name: cd
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Playbook
        run: sudo ansible-playbook -vv web.yaml
      - name: run deployment with kubernetes
        run: sudo kubectl apply -f deploy.yaml
        
