name: cd
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Playbook
        run: sudo ansible-playbook -vv web.yaml
      - name: eks
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - name: install eks
        run: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: run deployment with kubernetes
        run: sudo kubectl apply -f deploy.yaml
        
