name: WF1
on: 
  schedule:
  - cron: "30,35 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
env: 
  var1: Wednesday
  

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      last_name: Sue
    steps:
      - name: first step
        run: hostname
        if: runner.os == 'Windows'
      - name: get OS
        run: cet /etc/os-release
        if: runner.os != 'Windows'
        continue-on-error: true
      - name: sleep for 5 secs
        run: sleep 5
        if: github.event_name == 'push'
      - name: test var
        run: echo "First name is $first_name. Last name is $last_name"
        env:
          first_name: Weili
      - name: multiline run
        run: |
          echo running a multiline step
          echo "First name is $first_name. Last name is $last_name"
          echo Today is $var1
          echo mkdir weili
          echo cd weili
          echo touch file1

  test:
    runs-on: ubuntu-latest
    needs: build
    # continue-on-error: true
    steps:
      - name: print output
        run: |
          echo "Today is $var1"
          echo "First name is $first_name. Last name is $last_name"
      - name: job2 2nd step
        run: cat /etc/os-release
      - name: job2 get hostname
        run: hostname
      - name: sleep for 10 secs
        run: slep 10
      - name: test
        run: echo job2 completed

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always () }}
    steps:
      - name: print output
        run: |
          echo "Today is $var1"
          echo "First name is $first_name. Last name is $last_name"
      - name: job2 2nd step
        run: cat /etc/os-release
      - name: job2 get hostname
        run: hostname
      - name: sleep for 10 secs
        run: sleep 10
      - name: test
        run: echo job2 completed
