name: WF1
on: 
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "hello from job1 - push"
      - name: 2nd step
        run: echo "hello from step2"
