name: WF1
on: 
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1 first step
        run: echo "hello from job1"
      - name: job1 2nd step
        run: cat /etc/os-release

  job2:
    runs-on: self-hosted
    steps:
      - name: job2 first step
        run: echo "hello from job2"
      - name: job2 2nd step
        run: cat /etc/os-release
