name: WF1
on: 
  schedule:
  - cron: "30,35 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: hostname
      - name: get OS
        run: cat /etc/os-release
      - name: sleep for 60 secs
        run: sleep 60
        if: github.event_name == 'push'
      - name: multiline run
        run: |
          echo running a multiline step
          echo mkdir weili
          echo cd weili
          echo touch file1

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2 first step
        run: echo "hello from job2"
      - name: job2 2nd step
        run: cat /etc/os-release
      - name: job2 get hostname
        run: hostname
      - name: sleep for 60 secs
        run: sleep 60
      - name: test
        run: echo job2 completed
